services:
  mongo:
    container_name: mongo
    image: mongo:7.0-jammy
    ports:
      - '${DB_PORT:-27017}:27017'
    environment:
      - MONGO_INITDB_DATABASE=${DB_DATABASE_NAME}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - wdp301_se1833_nj_group_5_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}', '--appendonly', 'yes']
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - wdp301_se1833_nj_group_5_network
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - '${MINIO_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-9001}:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    command: server --console-address ":${MINIO_CONSOLE_PORT:-9001}" /data
    networks:
      - wdp301_se1833_nj_group_5_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    container_name: createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin};
      /usr/bin/mc mb myminio/${MINIO_BUCKET:-wdp301-se1833-nj-group-5-bucket} --ignore-existing;
      /usr/bin/mc policy set public myminio/${MINIO_BUCKET:-wdp301-se1833-nj-group-5-bucket};
      exit 0;
      "
    networks:
      - wdp301_se1833_nj_group_5_network

networks:
  wdp301_se1833_nj_group_5_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  minio_data:
