services:
  api:
    container_name: api
    depends_on:
      - mongo
      - redis
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - wdp301_se1833_nj_group_5_network

  mongo:
    container_name: mongo
    image: mongo:7.0-jammy
    ports:
      - '27017:${DB_PORT}'
    environment:
      - MONGO_INITDB_DATABASE=${DB_DATABASE_NAME}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - wdp301_se1833_nj_group_5_network

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}', '--appendonly', 'yes']
    ports:
      - '6379:${REDIS_PORT}'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - wdp301_se1833_nj_group_5_network

networks:
  wdp301_se1833_nj_group_5_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
